export default {
  data: {
    id: 'wdyBhBKaDP',
    meta: {
      mode: 'live',
    },
    type: 'orders',
    links: {
      self: '/api/orders/wdyBhBKaDP',
    },
    attributes: {
      guest: false,
      token: '5854089fc81bc8f9c8a75b334055bc87',
      number: 118957,
      status: 'pending',
      cart_url: null,
      editable: true,
      metadata: {},
      tax_rate: null,
      placeable: true,
      placed_at: null,
      reference: '',
      terms_url: null,
      created_at: '2019-10-04T15:28:09.340Z',
      return_url: null,
      skus_count: 1,
      updated_at: '2019-10-04T15:28:45.727Z',
      approved_at: null,
      coupon_code: null,
      privacy_url: null,
      cancelled_at: null,
      checkout_url: 'https://test-checkout.com/wdyBhBKaDP',
      country_code: 'IT',
      tax_included: true,
      currency_code: 'EUR',
      language_code: 'en',
      customer_email: 'foo@bar.com',
      payment_status: 'unpaid',
      freight_taxable: null,
      shipments_count: 1,
      fees_amount_cents: 0,
      fees_amount_float: 0,
      fulfillment_status: 'unfulfilled',
      payment_updated_at: null,
      total_amount_cents: 100,
      total_amount_float: 1,
      discount_amount_cents: 0,
      discount_amount_float: 0,
      formatted_fees_amount: '€0,00',
      requires_billing_info: false,
      shipping_amount_cents: 0,
      shipping_amount_float: 0,
      subtotal_amount_cents: 100,
      subtotal_amount_float: 1,
      formatted_total_amount: '€1,00',
      fulfillment_updated_at: null,
      payment_source_details: {},
      total_tax_amount_cents: 0,
      total_tax_amount_float: 0,
      line_item_options_count: 0,
      discount_tax_amount_cents: 0,
      discount_tax_amount_float: 0,
      formatted_discount_amount: '€0,00',
      formatted_shipping_amount: '€0,00',
      formatted_subtotal_amount: '€1,00',
      shipping_tax_amount_cents: 0,
      shipping_tax_amount_float: 0,
      subtotal_tax_amount_cents: 0,
      subtotal_tax_amount_float: 0,
      formatted_total_tax_amount: '€0,00',
      shipping_country_code_lock: null,
      total_taxable_amount_cents: 100,
      total_taxable_amount_float: 1,
      payment_method_amount_cents: 0,
      payment_method_amount_float: 0,
      discount_taxable_amount_cents: 0,
      discount_taxable_amount_float: 0,
      formatted_discount_tax_amount: '€0,00',
      formatted_shipping_tax_amount: '€0,00',
      formatted_subtotal_tax_amount: '€0,00',
      shipping_taxable_amount_cents: 0,
      shipping_taxable_amount_float: 0,
      subtotal_taxable_amount_cents: 100,
      subtotal_taxable_amount_float: 1,
      total_amount_with_taxes_cents: 100,
      total_amount_with_taxes_float: 1,
      formatted_total_taxable_amount: '€1,00',
      formatted_payment_method_amount: '€0,00',
      payment_method_tax_amount_cents: 0,
      payment_method_tax_amount_float: 0,
      formatted_discount_taxable_amount: '€0,00',
      formatted_shipping_taxable_amount: '€0,00',
      formatted_subtotal_taxable_amount: '€1,00',
      formatted_total_amount_with_taxes: '€1,00',
      formatted_payment_method_tax_amount: '€0,00',
      payment_method_taxable_amount_cents: 0,
      payment_method_taxable_amount_float: 0,
      formatted_payment_method_taxable_amount: '€0,00',
    },
    relationships: {
      market: {
        links: {
          self: '/api/orders/wdyBhBKaDP/relationships/market',
          related: '/api/orders/wdyBhBKaDP/market',
        },
      },
      customer: {
        links: {
          self: '/api/orders/wdyBhBKaDP/relationships/customer',
          related: '/api/orders/wdyBhBKaDP/customer',
        },
      },
      shipments: {
        links: {
          self: '/api/orders/wdyBhBKaDP/relationships/shipments',
          related: '/api/orders/wdyBhBKaDP/shipments',
        },
      },
      line_items: {
        data: [
          {
            id: 'vbmetOjnBk',
            type: 'line_items',
          },
          {
            id: 'yeYRtGLrWy',
            type: 'line_items',
          },
          {
            id: 'kdPgtXKqlk',
            type: 'line_items',
          },
        ],
        links: {
          self: '/api/orders/wdyBhBKaDP/relationships/line_items',
          related: '/api/orders/wdyBhBKaDP/line_items',
        },
      },
      payment_method: {
        links: {
          self: '/api/orders/wdyBhBKaDP/relationships/payment_method',
          related: '/api/orders/wdyBhBKaDP/payment_method',
        },
      },
      payment_source: {
        links: {
          self: '/api/orders/wdyBhBKaDP/relationships/payment_source',
          related: '/api/orders/wdyBhBKaDP/payment_source',
        },
      },
      billing_address: {
        data: {
          id: 'VWlrkuprVB',
          type: 'addresses',
        },
        links: {
          self: '/api/orders/wdyBhBKaDP/relationships/billing_address',
          related: '/api/orders/wdyBhBKaDP/billing_address',
        },
      },
      shipping_address: {
        data: {
          id: 'KWgnguzrmd',
          type: 'addresses',
        },
        links: {
          self: '/api/orders/wdyBhBKaDP/relationships/shipping_address',
          related: '/api/orders/wdyBhBKaDP/shipping_address',
        },
      },
      available_payment_methods: {
        links: {
          self: '/api/orders/wdyBhBKaDP/relationships/available_payment_methods',
          related: '/api/orders/wdyBhBKaDP/available_payment_methods',
        },
      },
    },
  },
  included: [
    {
      id: 'KWgnguzrmd',
      meta: {
        mode: 'live',
      },
      type: 'addresses',
      links: {
        self: '/api/addresses/KWgnguzrmd',
      },
      attributes: {
        lat: null,
        lng: null,
        city: 'Rome',
        name: 'Foo Bar, Via Roma 1,  12345 Roma RM (IT) 123',
        email: null,
        notes: null,
        phone: '123',
        line_1: 'Via Roma 1',
        line_2: '',
        company: null,
        map_url: null,
        business: false,
        metadata: {},
        zip_code: '35035',
        full_name: 'foo bar',
        last_name: 'bar',
        reference: null,
        created_at: '2019-10-04T15:28:40.036Z',
        first_name: 'foo',
        state_code: 'PD',
        updated_at: '2019-10-04T15:28:40.036Z',
        is_geocoded: false,
        billing_info: '',
        country_code: 'IT',
        full_address: 'Foo Bar, Via Roma 1,  12345 Roma RM (IT) 123',
        is_localized: false,
        provider_name: null,
        static_map_url: null,
      },
      relationships: {
        geocoder: {
          links: {
            self: '/api/addresses/KWgnguzrmd/relationships/geocoder',
            related: '/api/addresses/KWgnguzrmd/geocoder',
          },
        },
      },
    },
    {
      id: 'VWlrkuprVB',
      meta: {
        mode: 'live',
      },
      type: 'addresses',
      links: {
        self: '/api/addresses/VWlrkuprVB',
      },
      attributes: {
        lat: null,
        lng: null,
        city: 'Rome',
        name: 'Foo Bar, Via Roma 1,  12345 Roma RM (IT) 123',
        email: null,
        notes: null,
        phone: '123',
        line_1: 'Via Roma 1',
        line_2: '',
        company: null,
        map_url: null,
        business: false,
        metadata: {},
        zip_code: '35035',
        full_name: 'foo bar',
        last_name: 'bar',
        reference: null,
        created_at: '2019-10-04T15:28:40.036Z',
        first_name: 'foo',
        state_code: 'PD',
        updated_at: '2019-10-04T15:28:40.036Z',
        is_geocoded: false,
        billing_info: '',
        country_code: 'IT',
        full_address: 'Foo Bar, Via Roma 1,  12345 Roma RM (IT) 123',
        is_localized: false,
        provider_name: null,
        static_map_url: null,
      },
      relationships: {
        geocoder: {
          links: {
            self: '/api/addresses/VWlrkuprVB/relationships/geocoder',
            related: '/api/addresses/VWlrkuprVB/geocoder',
          },
        },
      },
    },
    {
      id: 'vbmetOjnBk',
      meta: {
        mode: 'live',
      },
      type: 'line_items',
      links: {
        self: '/api/line_items/vbmetOjnBk',
      },
      attributes: {
        name: 'Stripe Payment',
        metadata: {},
        quantity: 1,
        sku_code: null,
        tax_rate: null,
        image_url: null,
        item_type: 'payment_methods',
        reference: null,
        created_at: '2019-10-04T15:28:44.924Z',
        updated_at: '2019-10-04T15:28:44.924Z',
        currency_code: 'EUR',
        tax_breakdown: {},
        unit_amount_cents: 0,
        unit_amount_float: 0,
        total_amount_cents: 0,
        total_amount_float: 0,
        options_amount_cents: 0,
        options_amount_float: 0,
        formatted_unit_amount: '€0,00',
        formatted_total_amount: '€0,00',
        formatted_options_amount: '€0,00',
      },
      relationships: {
        item: {
          links: {
            self: '/api/line_items/vbmetOjnBk/relationships/item',
            related: '/api/line_items/vbmetOjnBk/item',
          },
        },
        order: {
          links: {
            self: '/api/line_items/vbmetOjnBk/relationships/order',
            related: '/api/line_items/vbmetOjnBk/order',
          },
        },
        line_item_options: {
          links: {
            self: '/api/line_items/vbmetOjnBk/relationships/line_item_options',
            related: '/api/line_items/vbmetOjnBk/line_item_options',
          },
        },
      },
    },
    {
      id: 'yeYRtGLrWy',
      meta: {
        mode: 'live',
      },
      type: 'line_items',
      links: {
        self: '/api/line_items/yeYRtGLrWy',
      },
      attributes: {
        name: 'Shipment #118957/S/001',
        metadata: {},
        quantity: 1,
        sku_code: null,
        tax_rate: null,
        image_url: null,
        item_type: 'shipments',
        reference: null,
        created_at: '2019-10-04T15:28:42.236Z',
        updated_at: '2019-10-04T15:28:42.236Z',
        currency_code: 'EUR',
        tax_breakdown: {},
        unit_amount_cents: 0,
        unit_amount_float: 0,
        total_amount_cents: 0,
        total_amount_float: 0,
        options_amount_cents: 0,
        options_amount_float: 0,
        formatted_unit_amount: '€0,00',
        formatted_total_amount: '€0,00',
        formatted_options_amount: '€0,00',
      },
      relationships: {
        item: {
          links: {
            self: '/api/line_items/yeYRtGLrWy/relationships/item',
            related: '/api/line_items/yeYRtGLrWy/item',
          },
        },
        order: {
          links: {
            self: '/api/line_items/yeYRtGLrWy/relationships/order',
            related: '/api/line_items/yeYRtGLrWy/order',
          },
        },
        line_item_options: {
          links: {
            self: '/api/line_items/yeYRtGLrWy/relationships/line_item_options',
            related: '/api/line_items/yeYRtGLrWy/line_item_options',
          },
        },
      },
    },
    {
      id: 'kdPgtXKqlk',
      meta: {
        mode: 'live',
      },
      type: 'line_items',
      links: {
        self: '/api/line_items/kdPgtXKqlk',
      },
      attributes: {
        name: 'test product',
        metadata: {},
        quantity: 1,
        sku_code: 'test',
        tax_rate: null,
        image_url: '',
        item_type: 'skus',
        reference: null,
        created_at: '2019-10-04T15:28:17.918Z',
        updated_at: '2019-10-04T15:28:17.918Z',
        currency_code: 'EUR',
        tax_breakdown: {},
        unit_amount_cents: 100,
        unit_amount_float: 1,
        total_amount_cents: 100,
        total_amount_float: 1,
        options_amount_cents: 0,
        options_amount_float: 0,
        formatted_unit_amount: '€1,00',
        formatted_total_amount: '€1,00',
        formatted_options_amount: '€0,00',
      },
      relationships: {
        item: {
          links: {
            self: '/api/line_items/kdPgtXKqlk/relationships/item',
            related: '/api/line_items/kdPgtXKqlk/item',
          },
        },
        order: {
          links: {
            self: '/api/line_items/kdPgtXKqlk/relationships/order',
            related: '/api/line_items/kdPgtXKqlk/order',
          },
        },
        line_item_options: {
          links: {
            self: '/api/line_items/kdPgtXKqlk/relationships/line_item_options',
            related: '/api/line_items/kdPgtXKqlk/line_item_options',
          },
        },
      },
    },
  ],
}
